---
# tasks file for lnd

- name: Get LND repo
  become_user: bitcoin
  shell: go get -d github.com/lightningnetwork/lnd
  environment:
    -  GOPATH: /home/bitcoin/go
    -  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/home/bitcoin/go/bin

- name: CD to LND repo and install
  become_user: bitcoin
  shell: make && make install
  environment:
    - GOPATH: /home/bitcoin/go
    - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/go/bin:/home/bitcoin/go/bin
  args:
    chdir: /home/bitcoin/go/src/github.com/lightningnetwork/lnd/
